/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidloft_JNI */

#ifndef _Included_com_droidloft_JNI
#define _Included_com_droidloft_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidloft_JNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_droidloft_JNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
